---
services: [docker]
language: python
dist: focal
git: {lfs_skip_smudge: true}
env:
  global:
  - "IMAGES=corpusops/sshd"
  - COPS_ROOT="$TRAVIS_BUILD_DIR/local/corpusops.bootstrap"
cache: {directories: ["$HOME/.cache/pip", "$COPS_ROOT"]}
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq -y --force-yes parallel
- >
  sudo bash -exc "python -c
  \"d='/etc/docker/daemon.json';
  import json;
  c = json.load(open(d));
  c['experimental'] = True;
  print(c);open(d, 'w').write(json.dumps(c))
  \"
  && systemctl restart docker"
- .ansible/scripts/download_corpusops.sh
- .ansible/scripts/setup_corpusops.sh
- echo "$DOCKER_PASSWORD" | docker login --password-stdin --username="$DOCKER_RELEASER"
script:
- docker build --squash -t $IMAGES .
after_success:
- local/corpusops.bootstrap/hacking/docker_release
