---
version: "3.7"
services:
  sshd:
    image: corpusops/sshd
    env_file: [.env]
    volumes:
    - ./keys:/etc/authorized_keys.in
    - ./hostkeys:/etc/ssh/keys.in
    - keys:/etc/ssh/keys
    - ./supervisor.d/sshd:/etc/supervisor.d/sshd
    - ./supervisor.d/fail2ban:/etc/supervisor.d/fail2ban
    - ./entry.sh:/entry.sh
    - ./fail2ban-supervisor.sh:/fail2ban-supervisor.sh
    - ${SSHD_CONFIG:-./sshd_config.in}:/etc/ssh/sshd_config.in
    - fail2ban:/var/lib/fail2ban
    - ./fail2ban:/fail2ban
    restart: always
    cap_add: [NET_ADMIN, NET_RAW]
    ports:
    - "${BINDIP:-0.0.0.0}:${OUTPORT:-55555}:22"
volumes:
  fail2ban:
  keys:
